### ISSUE TITLE
Define consistent approach to Tuples and Singletons

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#133]
LS-007 (https://lists.oasis-open.org/archives/openc2-comment/201811/msg00004.html):
> There an almost-persistent blurring of Language and Serialization that is pretty consistent, and that is concerning to me.
> 
> In the language of the OMG, the Language and the promised-but-not-here Architecture section of the Language, is in effect the PIM (Platform Independent Model), and each of its Serialization/Binding documents is a Platform Specific Model (PSM). One of the Profiles, i.e., the Actuator Profile, should be expressed in the PIM, but instantiable in each PSM. 
> 
> The PIM should support all the PSMs, but not specify one. It is an artifact of development and current thinking that the TC has opted to express the language and information model using JSON, but a PIM is still fundamentally abstract, that is, it should not interfere with or dictate the possible PSMs.
>
> The Language document explicitly allows (but does not require) multiple in many places. A message MAY contain many commands. A command MAY contain many Targets. A PSM MAY constrain a message to be a single one of each, Command and Target.
>
> If (as seems the case) the JSON Binding is restricting to one command and one target. That is a fine decision for a PSM, and I have no complaint about that.
>
> The architecture, though anticipates some other interactions. These include:
>
> 1. A single message having multiple commands. At a later time, it may be appropriate (as Duncan’s note suggests) to change or revoke a specific one of these commands.
> 2. A Target may wish to respond to individual commands with separate messages.
> 3. A Bridge device may need to unpack a multi-command message into multiple messages as it bridges a command to a different PSM
> 4. A Bridge device may need to unpack a single-command message into multiple single-target messages as it bridges a command to a different PSM.
> 5. A Command or Message may need to be re-transmitted, either because of some sort of race state in the target (it may be under attack, after all) or for incorporation into a suite of responses/commands to a particular situation or incident.
>
> In each of these cases, it is troublesome to have blurring between the transport mechanism (which would include header info) and the message payload.
>
> That said, IF a PSM restricts a Message to a single Command, and IF a PSM expects a MessageID within the command, then it MAY be reasonable to make the MessageID and CommandID identical. Alternately, it is reasonable that IF a PSM requires a single command inside a Message, to require them to be the same.

**Comment by davaya** [comment]
The intent is to make clear the separations you describe, and eliminate any blurriness:

1. The language, as specified using the JADN table format (Sections 3.3 and 3.4) and the JADN JSON format (Annex A) are a PIM.
2. The serialization rules in Section 3.1.5 define one specific PSM.   Other serialization rules / PSMs are anticipated in other documents.
3. All actuator profiles define an actuator PIM (that inherits from the language PIM) and are expressible in all PSMs.
4. The language PIM does not allow multiple commands per message or multiple target types per command.  It is trivial, but necessary, to define new data types (e.g., OpenC2-Commands = ArrayOf(OpenC2-Command) if the TC wishes a message to carry multiple commands.  It is necessary to define a new structure, e.g., OpenC2-Command-Type2 if the TC wished to allow multiple target types in one command.  The TC explicitly rejected that idea, preferring to keep each command as an atomic action.  Multiples is not a serialization issue; no PSM can instantiate multiples where the PIM is designed to not allow them.
5. New PIM types to support the additional interactions will need to be designed; in most cases the current types do not.
6. Neither "MessageID" nor "CommandID" are defined in OpenC2.  The behavior of "request-id" should be defined in Section 3.2 - a command transmitted from A to B over reliable transport at time X has a different request-id than the identical command transmitted from A to B at time Y (reliable transport means that retries of the same request don't change the request-id).   If the identical command were always transmitted with the same associated value regardless of source, destination, and time, it would be reasonable to call that value a "CommandID' because it behaves similarly to a hash value over the command content, not a hash value over the full message.

**Comment by romanojd** [comment]
We've made a number of changes to how serialization is addressed. The other points in the comment about architecture sections, and PIMs vs. PSMs, should be addressed in a future version of the specification. I am going to mark this issue for the **future** and recommend that it be closed for v1.0-csprd01.

**Comment by romanojd** [comment]
LSC Meeting: 3/19/2019: There were no objections to labeling this for the "future" and closing this issue.
