### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#153]
LS-023 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):
> 11-43: Scope is a JSON serialization. (1) Are other serializations permitted? Does this scope include protocol bindings? Suggest language that JSON is used in this document to define the encodings and message handling in this document. This implies that (1) JSON-based implementations MUST use the encoding and message handling indicated in this specification (and in the JADN), and that other encodings and serializations (is there a difference?) must specify (the mapping between the encoding they use and this specification and (2) how they handle the message routing functions in this specification. (Note: I think that what I call the message handling functions cleanly delimited by the specification that they appear in the HTTP header.

LS-029 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):
> 16-21:38. Are these rules for JSON Serialization, or conformance points for non-JSON serialization or…We seem to be bleeding between levels here. Suggest a section on JSON serialization and moving this section to there. Suggest moving sections 3.1.5.1 and section 3.1.5.2

LS-041 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):
> 20-45:21:15 May be bridging space between information model and serialization requirements. If specific serialization requirements are expected, they should be described with others in the JSO encoding section.

LS-096 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00025.html):

> Pg 15 line 38 section 3.1.5. Serialization
> Current wording is 
> > “OpenC2 is agnostic of any particular serialization; however, implementations MUST support JSON serialization in accordance with RFC 7493 and additional requirements specified in the following table.”
> 
> I agree with the spirit off the statement but I believe the current wording can be circumvented and would prefer that it be more specific. I agree we MAY have other serializations in the future. At the moment, we do not. I also would prefer to refer to what we are specifying, not to ‘implementations’. We define the interface, not how to implement it. I propose changing to:
> 
> > “All interfaces using the OpenC2 language MUST use JSON serialization in accordance with RFC 7493 and the additional requirements specified in the following table. The language MAY be extended to use other serializations in addition to JSON, but must interwork with systems using JSON serialization.”

**Comment by dlemire60** [comment]
The resolution of this issue may influence HTTPS Spec [issue 10](https://github.com/oasis-tcs/openc2-impl-https/issues/10).

**Comment by davaya** [comment]
**LS-023:** The scope of this document (LS v1.0) is:

> 3. a syntax that defines the structure of commands and responses
> 4. a JSON serialization of OpenC2 commands and responses

The syntax is specified in a serialization-agnostic manner by the JADN tables of Sections 3.3 and 3.4.  The JSON serialization of that syntax is specified in Section 3.1.5.   Those two together define valid OpenC2 content when a "product" (pick your favorite word for implementation) successfully passes conformance requirements of both the language spec and the https transfer spec.  

A different transfer spec could define different serialization rules (specifying how to serialize each type listed in Section 3.1.5) and define how to invoke those rules (presumably using a different Content-Type header if it is HTTP-based, or by other means.)   A "product" can support both transfer specs without being declared non-conformant with one of them.

**LS-029:**  p15 line 38 through p16 line 20 specify "JSON serialization requirements", as stated in

>  MUST support JSON serialization in accordance with RFC
> 7493 and additional requirements specified in the following table.

16 - 21:38 specify requirements that apply to all serialization methods including JSON.   It might be helpful to insert a subsection heading "3.1.5.1 JSON serialization" at p15 line 38, and renumber the general serialization subsections at 16-21:38.   Or the two general serialization subsections could be shown first, and move the JSON text and table down to a new subsection 3.1.5.3.

**LS-041:** Don't understand the comment.  Section 3.3.2 defines the abstract syntax of an OpenC2 Response, just as section 3.3.1 defines the abstract syntax of an OpenC2 Command.   Both command and response are defined using the JADN datatypes of section 3.1.1 and both MUST be serialized using the JSON serialization rules of Section 3.1.5 in order to conform to a transfer spec that uses JSON serialization.

**LS-096:**   The language does not need to be extended.   The language spec defines the abstract syntax that applies to all serializations.  The language spec also defines the JSON serialization rules that are invoked by the HTTPS transfer spec.   Every product that conforms to the HTTPS transfer spec MUST interoperate.

**Comment by davaya** [comment]
WRT LS-096: OASIS defines the term "implementation" in https://www.oasis-open.org/committees/ioc/glossary.htm:

**Conformance Testing** - testing to evaluate the adherence or non-adherence of an implementation to a specification.

* We define conformance requirements.
* Implementations are tested to ensure that they meet conformance requirements.
* Implementations that conform will interoperate (if our requirements are good).

"The language" does not interwork with anything.

**Comment by romanojd** [comment]
From Section 3.1.6, Serialization:
> OpenC2 is agnostic of any particular serialization; however, implementations MUST support JSON serialization in accordance with RFC 7493 and additional requirements specified in the following table.

From Section 5, Conformance:
> 5.3-2 MUST implement JSON serialization of generated Commands in accordance with RFC 7493.

Is there anything more we need to say? Recommend closing with no changes.

**Comment by romanojd** [comment]
LSC Meeting, 3/19/2019: There were no objections to closing this issue.
