### ISSUE TITLE
Number of Features

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#157]
LS-100 (https://www.oasis-open.org/apps/org/workgroup/openc2/email/archives/201812/msg00029.html):

> Pg 25 page 15ish - section 3.4.1.6 has 0..n but should have 1..n. If present, must have 1 or more feature (similar to DKS11). We need to do better distinguishing between the key (and whether present or not, a 0..1 cardinality) and the values (which are 1..n cardinality).

**Comment by davaya** [comment]
Target "features" has value "Features"  (section 3.3.1.2).

Features (section 3.4.1.6) is an array of length 0..n.   Annex B.3 contains an example query for two features.

The SLPF profile contains an example command with zero features:  "query features []".  This is a heartbeat request - the response contains no data, but the empty response indicates that the actuator is alive.

I prefer that the heartbeat query be retained - that use case has been proposed by the members.  If the TC prefers to remove that capability by requiring "query features" to contain at least one item, I don't object.

**Comment by jmbrule** [comment]
Agree with keeping the heartbeat, this was a use case presented to the Actuator Profile SC last summer

**Comment by davaya** [comment]
At the F2F we discussed whether a command "query features []" (a query for zero features) should be permitted in order for a Producer to determine if a Consumer is responding to OpenC2 commands (a so-called "heartbeat" query), or whether the Producer must ask for at least one feature (e.g., "query features [profiles]" or "query features [versions]" in order to perform that check.

    Transmission Control Protocol (TCP) keepalives are an optional feature, and if included
    must default to off. The keepalive packet contains no data. In an Ethernet network,
    this results in frames of minimum size (64 bytes).
    --- https://en.wikipedia.org/wiki/Keepalive

IMO there is no reason to send artificial data when none is required to satisfy the heartbeat use case, but if L-SC consensus is to require queries to contain at least one feature, the syntax can be updated to require it.

Alternatives:
1. Zero-features query:
    * Minimum size commands and responses
    * Follows precedent for heartbeat/keepalive functions

2. Require query to contain one or more features to determine if Consumer is alive

3. Define a new "Heartbeat" target with NULL specifiers
    * All other targets have specifiers
    * Conformance requirements for 2 commands ("query features" and "query heartbeat") instead of 1
    * List of targets expanded to accommodate a niche requirement

**Comment by bberliner** [comment]
I'm fine with `query/features` with an empty array of features being a query that returns nothing (since that is exactly what was asked for).

An alternative interpretation of this might be that asking for nothing would return everything known by the consumer (i.e., would implicitly mean to respond with all known feature-related information in the response). However, being explicit is better here, I think, and there is value in a `ping` style request, so I do support Dave's Alternative 1 suggestion, given that he is including additional text to explain the behavior.

**Comment by romanojd** [comment]
Is everybody happy with pull request #234?

**Comment by romanojd** [comment]
LSC Meeting, 2/26/2019: There were no objections to applying pull request #234 and closing this issue.

**Comment by romanojd** [comment]
This issue was revisited because the pull request contained conflicts.

**Comment by romanojd** [comment]
LSC Meeting, 3/12/2019: There were no objections to applying pull request #234 and closing this issue.
