### ISSUE TITLE
Define "nsid"

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#212]
LS-044 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 22-23: Is nsid a normative term? Where is it defined?

**Comment by romanojd** [comment]
The namespace identifier is found in Section 3.4.3, which is being removed with the JADN schema definitions. But, this term is also found in Section 3.3.3, Imported Data. Do we need to keep this definition somewhere?

**Comment by jmbrule** [comment]
NSID has to be defined for the simple reason that we need to namespace the profiles (and imported data) so that the actuator arguments can be put in context.

**Comment by bberliner** [comment]
When I review Section 3.3.3, Imported Data, I do not have a clear understanding about what is being specified and how I might use it. An example is included, which is helpful but not sufficient. It shows something that looks like a Python `import` statement and then describes a custom `target` that presumably maps to something in that import. This all feels non-normative to me. As such, Section 3.3.3 has a worthy goal (allow for standardized external data models to be imported instead of re-defining them in your actuator profile), but the section does not deliver on that promise. Such things can be done with JSON-Schema, as they have already defined a way to reference external schema modules. We need to re-think Section 3.3.3.

**Comment by davaya** [comment]
The current section 3.3.3 needs to be divided into two sections.   The import mechanism is JADN and will be moved to section 3.1.   The extension mechanism is an OpenC2 convention for importing non-standard actuator profiles under an IANA or an unregistered namespace.

The SLPF profile provides a more complete example of the process:
1) In an actuator profile, define actuator-specific Targets, Actuator Specifiers, Command Arguments, and Results and list those four types in a JADN export statement.  The export statement is a hint to tooling that those are top-level types that are expected to be imported by some other schema - it inhibits warnings that those type definitions are unreferenced within the profile schema.
2) In the Language schema used in a particular OpenC2 product, list imported schemas in a JADN import statement.  The import statement assigns the namespace id (nsid) to the unique name of the imported module.
3) In the Language schema used in the product, include the imported nsid in the list of supported Targets, Actuators, Command Arguments, and Results to allow the profile definitions to be used in the product.

In an effort to avoid using the word JADN in the language spec we tried to limit the amount of JADN-specific information in Section 3.1 to an absolute minimum.  But it's clear that more of that information must be documented to understand how imports (as well as JADN type and field options) work.

**Comment by romanojd** [comment]
Per the LSC Meeting, 1/22/2019, @davaya is proposing changes to the "Imported Data" section that will address this issue.

**Comment by romanojd** [comment]
See pull request #240.

**Comment by romanojd** [comment]
Addressed by resolution to #242. Agreed to close at 2/13/2019 LSC Meeting.
