### ISSUE TITLE
Action-Targets (Array)

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#220]
LS-053 (https://lists.oasis-open.org/archives/openc2-comment/201812/msg00000.html):

> 28-37 What is the relationship between this Target [_in the Action-Targets array_] and the Targets in the Command table?

**Comment by jmbrule** [comment]
The 'target' in the array and 'targets' in the command table are the same.  In the 'command table' we are defining a commands components, in 3.4.2.15 we are talking about hte action target pairs (that is, the commands that the actuator supports as communicated by action target pairs in response to a query features command)

**Comment by romanojd** [comment]
I'm adding this to this week's `focus_review` topics. Please also review the syntax of this datatype.

**Comment by bberliner** [comment]
One confusing aspect of the spec is that it has custom syntax to describe the data model and the reader needs to do some searching to resolve things currently. I think part of the confusion in this issue is that the Type in the table is `Target.*` and the reader simply must know to go find where the `.*` suffix is discussed. It is discussed in Section 3.1.4.

But the description in section 3.1.4 adds some confusion. Section 3.1.4 does describe what a `.*` means, but it is a pretty loose description, using words like `derived` and `auto-generated`. When you know what the expected answer would be, `auto-generated` schema is great, but it’s impossible for somebody who doesn’t know how to auto-generate the perfect and correct thing always (which, to me, makes 3.1.4 non-normative).

For example, in Section 3.1.4, I can kinda figure it out for `Choice` (like a `Target` is) because Choice is an enumeration, so you can only have one of them. However, the description there says that I can apply the `.*` to Maps and Records too. But I could not tell you what the auto-generated enumeration of a Map or Record would be. No idea.

Our spec only uses `.*` currently for Choice items (only for `Target` and `JADN-Type`). So, this is another example of JADN overreach in the Language Spec. JADN may support auto-generated Map and Records as well, but our spec doesn’t use it. So, if I were being strict, I’d have a new issue to say that Map/Record language should be removed from section 3.1.4 and that the usage with a Choice, like `Target` would work exactly the way that we want (would be the string name of the target, in this case). Or, they Type in the Table would change to something more self-explanatory, like `Target.name` perhaps.

For this issue, I think the description in the spec does give a hint at what it expects when it says `The targets are enumerated values derived from the set of Target`. However, that statement is likely not clear enough, since it's not clear to me what "enumerated values" means in this context. So, some clearer wording would likely clear the confusion.

**Comment by davaya** [comment]
The .* notation "auto-generates" (produces) an Enumerated data type.   The input to that production is a Choice, Map, or Record data type.   The purpose of auto-generation is to ensure consistency between a pointer to something (e.g., the name of a Target) and the thing being pointed to (the Target with that name).

An example of how the Enumerated type is generated (strip off all but the ID and Name columns of the referenced type) should help.

A Choice is a Map where instances are constrained to have exactly one field.   An instance of a Map can have more than one field.   A hypothetical auto-generated Enumerated item could identify one field of a Map.  A hypothetical ArrayOf(auto-generated Enumerated) could identify one or more fields of a Map.   A hypothetical use case might be to support database "views" where a table contains 10 columns but a specific view of that table contains only 4.   Each of those 4 columns must exist in the original 10; the view must be a subset of the original.

**Comment by romanojd** [comment]
Per the LSC Meeting, 2/19/2019, Dave Kemp agreed to develop a pull request to update the section on "derived enumerations" to resolve this issue. This will be presented at the next LSC Meeting.

**Comment by romanojd** [comment]
Pull request #257 was updated.

**Comment by romanojd** [comment]
There were no objections to applying the pull request and closing this issue at the LSC Meeting, 2/26/2019.
