### ISSUE TITLE
Is Actuator correct word?

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#398]
The word actuator was discussed at a working meeting a few weeks ago. Apparently the word causes some misunderstandings. Changing would be a breaking fix (ie would cause to increment to V2.0). Initial proposal was to defer for awhile but consensus was reached that it would be better to do sooner rather than later.

What should the word be?

The language spec defines actuator:
```
Actuator: The function performed by the Consumer that executes the Command (e.g.,
'Stateless Packet Filtering').
```
If you have a proposed word to replace it, add a comment below. If you like one of the alternatives someone put below, then give it a thumbs up. If you are against a particular word, give it a thumbs down.

**Comment by sparrell** [comment]
Leave it as is with 'actuator"

**Comment by sparrell** [comment]
'actor'

**Comment by sparrell** [comment]
'function'

**Comment by sparrell** [comment]
'functional component'

**Comment by sparrell** [comment]
"executor"

**Comment by sparrell** [comment]
"performer"

**Comment by sparrell** [comment]
"agent"

**Comment by sparrell** [comment]
"action doer"

**Comment by davaya** [comment]
profile

**Comment by dlemire60** [comment]
This was discussed at the 8/3 working meeting, and @davaya clarified that the real issue is the use of the term "actuator" in the specification where "profile" would be more appropriate. This will be a breaking change, as it affects the message content definition, and should be handled promptly. @davaya will be preparing a corresponding PR.
