### ISSUE TITLE
Capabilities Discovery

### ISSUE THREAD

**Issue by romanojd** [oasis-tcs/openc2-oc2ls#40]
`query`/`openc2` was conceived to allow for an OpenC2 Consumer to request an Actuator's list of capabilities. We need detailed examples/scenarios to be able to fully develop this case.

There is also a [suggestion](https://docs.google.com/document/d/1ZK6_2vpC_SsZJnKdEM-gQ335EeHV7iY7yJLZqRLcjio/edit?disco=AAAABooym6Y) to rename the target to `capability_list` or something similar to be more descriptive.

**Comment by dmg2** [comment]
As I recall this is in the target list. Would make sense to me that the target be called "actuator". We then could not only query the actuator for capabilities, but we could also C2 the actuator itself. I want to be clear here, I am making a distinction between choosing an actuator to affect a target and having that target be the actuator itself. It is likely that when you choose an actuator as a target that the actuator chosen to carry out this task will be the same. However this would allow us to take action on actuators themselves.  One usecase could be turning on and off capability on an actuator, another could be adding or removing users who have access to control a given actuator.

**Comment by jmbrule** [comment]
The discovery procedures that this issue is talking is not limited to the 'target list'.   The query openc2:openc2 command will capture the profile(s) supported.  DMG2's point is a good one in that it highlights that we are talking about a 'query' procedure to discover capabilities and/or negotiate, not so much for 'selecting' an actuator

**Comment by sparrell** [comment]
use cases now exist.
