### ISSUE TITLE
Set/Get/... CRUD actions have (Jason say what goes here)

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#69]
The four basic data processing functions are Create, Read, Update, and Delete ([CRUD](https://en.wikipedia.org/wiki/Create,_read,_update_and_delete)). In OpenC2, we use the following actions, respectively: create, query, set, delete.

We need to consider the structure of the OpenC2 Command when issuing these actions. What TARGET(s) are appropriate to pair with these actions? What additional parameters are required to issue complete commands? How are any additional parameters structured?

**Comment by jmbrule** [comment]
This issue is similar to issue #70 (Where put the 'to' when target is the 'from' eg redirect this one to that one) in that the three approaches that one would use for 'redirect to' would work for CRUD.  Suggest that we merge the issue with 70 and close number 69.   At the highest level, we need to decide 'create action options', 'create openc2 specific targets' or 'use the preexisting command option' field.

**Comment by jmbrule** [comment]
There was a suggestion to close this issue 23 months ago and has been no discussion since.  Suggest close

**Comment by dlemire60** [comment]
I believe the questions asked in the first post for this issue are best addressed in the context of actuator profiles that use these actions, rather than at the LS level. I support closing this issue.

**Comment by dlemire60** [comment]
Discussed at Triage, @sparrell agrees with closing.
