### ISSUE TITLE
Where put the 'to' when target is the 'from' eg recdirect thisone to thatone

### ISSUE THREAD

**Issue by sparrell** [oasis-tcs/openc2-oc2ls#70]
The redirect command has the target (the bad url) and a new url to redirect it to (the new url). Where does the new url go?

In the Looking Glass use case it was made a action option (a new construct). Some propose (verbally - they should make a use case or propose spec text) it would go in target option. Others propose (ditto) it go in command options.

Spec needs to pick one way to do this for all the 'to/from' type commands

**Comment by jmbrule** [comment]
Commands such as set, redirect, update offer some challenges, and one of the underlying issues is the distinction between the 'target' and the 'actuator' is somewhat blurred.  

The "question" is where do we put the 'set to value'? Not stating these are the 'only' possibilities, but here are three high level approaches: 

ONE:  Define action specific options for some of the actions such as ‘set’.  That raises an issue because would end up with ~25 or 30 enumerated actions and ~ 5 or 10 'choice' actions.  We also lose the decoupling of the actions from the other fields.  

TWO:  Put it in as a key value pair in the command-options field.  The idea being if you wanted to turn on logging you would do something like ‘set [some target] [some actuator][logging=true]’.  There is a potential issue with this approach. We have a design principle where we keep the language at the 'universal' level and push the complexity to the profiles for particular actuators so the 'command-option' approach will lead to the need to identify the actuator profile.  For the 'set' use case is not really an issue, but for other actions, some of these modifiers are only applicable to a subset of the actuators.  

THREE:  Put it in the target data model (or even create a target type to meet the need).  For example, if you wanted to turn on logging, we can create the target type and would have something like ‘set [target type: ‘x-config’, option: logging=true ]’

**Comment by jmbrule** [comment]
Of the three approaches, leveraging the command options field (TWO) is prob the most straightforward.

**Comment by sparrell** [comment]
resolved, goes in arg
